### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by Yele97** [Wenzhi-Ding/Weibo-Crawler#28]
![6ca6084c2e0a88e28291401796326a0](https://user-images.githubusercontent.com/115403829/194832324-ebb2242c-4e53-442a-a714-0fb81ac632e3.jpg)

**Comment by Wenzhi-Ding** [comment]
无法复现该错误。不过暂时先通过丢掉空值解决。根本原因可能在于搜索页面的正则表达式有问题。
